name: Preprocess Cache

on:
  workflow_dispatch:
  schedule:
    - cron: '15 15 * * 2'

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GEM_HOME: ${{ github.workspace }}/gems
      DATA_DIR: ${{ github.workspace }}/data-cache
      PACKAGE: ${{ github.workspace }}/data.tgz
    steps:
    - name: Check out repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Fetch and compress data
      run: |
        echo "AAA ${GEM_HOME}"
        ./fetch-data "${DATA_DIR}"
        tar --directory "${DATA_DIR}" --create --gzip --file "${PACKAGE}" .
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "$(date +%F)" --title "$(date +%F)" "${PACKAGE}"
